apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../gke
patches:
  - path: patch-prefill.yaml
  - path: patch-decode.yaml
  - path: patch_nixl_conn_decode.yaml
  - path: patch_nixl_conn_prefill.yaml
