apiVersion: v1
kind: Service
metadata:
  name: sglang-master-pod-k3
  namespace: default
  labels:
    app: distributed-sglang-k3
spec:
  clusterIP: None
  ports:
  - name: dist-port
    port: 20000
    protocol: TCP
    targetPort: 20000
  selector:
    app: distributed-sglang-k3
    apps.kubernetes.io/pod-index: "0"
  type: ClusterIP
