apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

labels:
  - pairs:
      llm-d.ai/model: Qwen3-14B
    includeSelectors: true
    includeTemplates: true

patches:
  - path: patch-decode.yaml
  - path: patch-prefill.yaml
