apiVersion: v1
kind: Service
metadata:
  name: pd-disaggregation-nvidia-gpu-sglang-decode
spec:
  publishNotReadyAddresses: true
  selector:
    llm-d.ai/role: decode
    llm-d.ai/guide: pd-disaggregation
  ports:
  - name: modelserver
    port: 8200
    targetPort: 8200
  - name: dist
    port: 5000
    targetPort: 5000
  - name: nixl
    port: 5600
    targetPort: 5600
